피드백 후 리팩토링
jpoh281/base_ball_game pull request #1
Opened 2022-06-19 11:44 UTC by jpoh281

2022-06-19 11:58 UTC, viiviii reviewed
![image](https://user-images.githubusercontent.com/75404713/174479753-d0a774cd-6f28-4c11-85bc-db75c89cd723.png)

2022-06-20 06:26 UTC, neoganjeol requested changes
더 잘게잘게 쪼개져서 보기 좋아진거같아요 
역할도 더 잘 분리된걸로 보이고요.

조금 더 생각해볼 코멘트를 드렸어요~
제가 해당 미션에 대한 이해도가 높지않아서 + dart를 잘 몰라서 이상한 코멘트가 있을수 있으니 잘 거르고 생각하셔요!

2022-06-20 06:26 UTC, neoganjeol commented on lib/controllers/base_ball_game_controller.dart
> +    var inning = Inning(answer);
innig객체를 이곳에서 만들어서 넘겨줘야 하는 이유가 있는걸까요???

2022-06-20 06:26 UTC, neoganjeol commented on lib/views/game_board.dart
>      return numbers;
view에서 제대로된 값인지 체크하니 어떠신가요? 
혹시 다른 view가 생기면 이와 같은 일을 또 해줘야할거같은데 혹시 어떻게 해결할 수 있을까요??

hint) number라는 클래스를 만들어 보는건 어떨까요??

2022-06-20 06:26 UTC, neoganjeol commented on lib/models/inning.dart
> +  bool get isWin => strikes == 3;
개인적으론 InnigResult가 사라진게 아쉬운거같아요 
Innig의 역할은 playBatting이고 이후의 결과는 따로 정리가 가능하지않을까요?

그렇다면 printInningResult의 if문도 줄일수 있을듯한데 어떻게 생각하세요?

2022-06-21 14:36 UTC, neoganjeol commented on lib/models/at_bat.dart
> +    }
👍 깔끔해진거같아요 혹시 좀 더 나가서 validate 메소드를 분리해보는건 어떨까요??

2022-06-21 14:36 UTC, neoganjeol commented on lib/models/inning.dart
> +    if (answers[i] == atBat.numbers[i]) {
answers가 의미하는건 어떤거에요?  atBat데이터를 꺼내지않고 비교할 순 없을까요?

2022-06-21 14:38 UTC, neoganjeol commented on lib/controllers/base_ball_game_controller.dart
> +    var atBat = board.getAnswer();
👍

2022-06-21 14:38 UTC, neoganjeol commented on lib/models/game.dart
> +    var inning = Inning(innings.length+1, atBat);
innings.length+1 의 결과는 무엇을 의미하는거에요?? 더 명시적으로 메소드로 추출해주는건 어떠할까요?

2022-06-21 14:38 UTC, neoganjeol commented on lib/models/batting_numbers.dart
> +class BattingNumbers {
At_bat에서 클래스명이 바뀌었군요 ㅋㅋㅋ

2022-06-21 14:39 UTC, neoganjeol commented on lib/models/inning_result.dart
> +class InningResult {
👍  뭔가 저는 한눈에 들어오는듯해요  
여기서 더욱더 케이스가 추가된다면 원래 하셨던것처럼 하위 클래스를 두는것도 방법일듯 해요!

2022-06-21 14:49 UTC, DynamicNam commented on lib/models/answer_numbers.dart
> +class AnswerNumbers {
다트는 파일명을 snake case를 쓰나 보네요
갓디디님 덕분에 다트코드 구경합니다 감사합니다 💯

2022-06-21 14:56 UTC, DynamicNam commented on lib/models/game.dart
>    void settingGame() {
단순히 동사 + 명사 느낌의 setGameAnswer 같은 naming이 조금 더 명확한 의미를 주지 않을까 싶습니당
그리고 refactoring의 결과로 setNumbers 하나를 호출하는 역할만 하게 된다면.......

그 역할에 맞는 이름으로 바꾸어 보는 것도 좋지 않을까 싶어요. 
그리고 아마도 이 함수는 외부에서는 호출되면 안될 것 같은데, 그런 의미에서 다른 파일들에서 해놓으신것처럼
함수이름앞에 언더바를 달아놓으면 좋을거 같다는 생각이 듭니다 👍

2022-06-21 14:57 UTC, DynamicNam commented on lib/models/inning.dart
> +    return result;
result라는 단어 자체가 크게 유의미하지 않으니

그냥 return atBat.play() 라고 해도 되지 않을까요?

2022-06-21 14:59 UTC, DynamicNam commented
무엇보다 역시 멋있다.... 감동적인 코드입니다.... 🥇

2022-06-21 15:19 UTC, jpoh281 commented on lib/models/batting_numbers.dart
> +class BattingNumbers {
네 그리고 다시 AtBat라는 클래스가 다른 역할로 생겼습니다. ㅋㅋㅋ

2022-06-21 15:20 UTC, jpoh281 commented on lib/models/inning.dart
> +    if (answers[i] == atBat.numbers[i]) {
마지막에 생긴 AtBat에서는 다른 방식으로 바꿨어용!

2022-06-21 15:22 UTC, jpoh281 commented on lib/models/game.dart
>    void settingGame() {
말씀하신 것처럼 최소한 setGameAnswer이나 setGame이 더 낫다는 생각이 드네요.
지금 해당 메소드는 외부에서 호출되고 있어서 구조를 바꿔봐야할 것 같아요.

2022-06-21 15:22 UTC, jpoh281 commented on lib/models/game.dart
> +    var inning = Inning(innings.length+1, atBat);
오 이부분은 생각못했는데 수정하면 좋을 것 같아요. 감사합니다.

2022-06-21 15:24 UTC, jpoh281 commented on lib/models/answer_numbers.dart
> +class AnswerNumbers {
다트 츄라이 해보시죠

2022-06-21 15:24 UTC, jpoh281 commented on lib/models/inning_result.dart
> +class InningResult {
오오 감사합니다.

2022-06-21 15:57 UTC, jpoh281 commented on lib/models/at_bat.dart
> +    }
이게 팩토리 내부에서 해당 클래스의 인스턴스 멤버(메소드, 필드)를 호출할 수 없더라구요.
1.  static 메소드로 validate를 만드느냐?
2.  top level 함수로 빼느냐?
3.  factory 내부에 메소드를 박느냐? 
셋 중에서 3번이 가장 깔끔하다고 판단했습니다.
지금 다시 생각했을 땐 테스트코드 생각하면 2번이 가장 좋은 것 같기도해요

2022-06-21 16:02 UTC, jpoh281 commented on lib/models/inning.dart
> +    return result;
맞습니다. 고쳐야겠어요 감사합니다.

2022-06-21 16:11 UTC, neoganjeol commented on lib/models/at_bat.dart
> +    }
제가 다트의 팩토리는 모르지만 제가 잡은 영역에서 인스턴스 멤버를 건드리는 부분이 있나요? 딱히 그런부분이 안보여서요.

2022-06-21 16:23 UTC, neoganjeol commented on lib/models/at_bat.dart
> +    if (answer.numbers[i] == batting.numbers[i]) {
answer.numbers 와 batting.numbers가 같을때 스트라이크 카운트가 올라가야한다면 이 조건을 좀 더 명확하게 해주는건 어떨까요? 

그리고 그렇게 메소드가 만들어진다면 혹시  AnswerNumbers나 BattingNumbers로 해당 메소들르 넘길수는 없을까요?
만약 넘기는게 어색하다면 새로운 클래스를 고려해보는건 어떨지 한번 고민해보셔요

2022-06-21 16:23 UTC, neoganjeol commented on lib/models/at_bat.dart
> +      battingResult.strikes++;
직접적으로 데이터를 수정하지 말고 메소드를 호출하는 형태로 바꿔보는건 어떨까요?

2022-06-21 16:23 UTC, neoganjeol commented on lib/models/at_bat.dart
> +    if (answer.numbers.contains(batting.numbers[i])) {
이 부분도  데이터값 비교로직을 AnswerNumbers나 BattingNumbers로 넘길순 없을까요?

2022-06-21 16:23 UTC, neoganjeol commented on lib/models/at_bat.dart
> +      battingResult.balls++;
직접적으로 데이터를 수정하지 말고 메소드를 호출하는 형태로 바꿔보는건 어떨까요?(2)

2022-06-21 16:23 UTC, neoganjeol commented on lib/models/batting_numbers.dart
> +    if (regExpResult.length != 3) {
만약 이 조건이 3개가 아니라 앞으로 다양한 정책을 고려하여 변경할수 있따면  어떻게 구현할 수 있을까요?

2022-06-21 23:28 UTC, jpoh281 commented on lib/models/at_bat.dart
> +    }
너간절님의 피드백이 validation을 팩토리로부터 내부 메소드로 빼라는 말씀으로 이해를 했었어요.

그래서 팩토리 외부로 validation 메소드를 빼내면 팩토리에서 사용하지못하게 되더라구요

2022-06-23 14:21 UTC, jpoh281 commented on lib/models/at_bat.dart
> +      battingResult.strikes++;
이부분은 바로 수정했습니다!

2022-06-23 14:21 UTC, jpoh281 commented on lib/models/at_bat.dart
> +      battingResult.balls++;
이부분은 바로 수정했습니다! (2)

2022-06-23 14:25 UTC, jpoh281 commented on lib/models/batting_numbers.dart
> +    if (regExpResult.length != 3) {
일단 3으로 하드코딩 된 숫자들은 constant의 상수로 변경했습니다.
만약 턴수, 숫자의 수를 변경한다면 뷰에서 입력받아서 컨트롤러를 통해서 조절하면 될 것 같아요.

2022-06-23 14:27 UTC, jpoh281 commented on lib/models/at_bat.dart
> +    if (answer.numbers.contains(batting.numbers[i])) {
contains 같은 경우는 매개변수를 하나만 보내면 되서 answerNumber로 보내면 쉽게 끝날 것 같습니다.

2022-06-23 14:31 UTC, jpoh281 commented on lib/models/at_bat.dart
> +    if (answer.numbers[i] == batting.numbers[i]) {
명확하게 하기위해서 조건식의 내용을 또 다른 private 메소드로 만들어서 보기 쉽게 만들었습니다.
다른 클래스로 옮기는 부분은 생각이 조금 더 필요할 것 같아요.

2022-06-24 01:35 UTC, neoganjeol commented on lib/models/batting_numbers.dart
> +    if (regExpResult.length != 3) {
오 좋은 생각인듯해요 
그럼 추가로 질문드리고 싶은게 ... 만약 length 비교같은게 아니라 로직 자체가 변경되어야 한다면요??

2022-06-24 01:38 UTC, neoganjeol commented on lib/models/at_bat.dart
> +    if (answer.numbers[i] == batting.numbers[i]) {
https://github.com/jpoh281/base_ball_game/pull/1/commits/61541a0b7725d1c7eaa5371c6bb10a340f1d5a63 수정된 커밋을 같이 댓글로 달아주시면 더 좋을거같아요 

메소드로 분리하니 더 보기좋은거같아요!
근데 strike, ball 인지 판단하는게 bat의 역할 맞을까요?? 
그 관점에서 보시면 어떻게 해결할 수 있을까요?

2022-06-24 01:41 UTC, neoganjeol commented on lib/controllers/base_ball_game_controller.dart
> +  final BaseBall game = BaseBall();
@jpoh281 
제가 잘 몰라서 그러는데 dart는 생성자에서 객체를 할당 해줄 수 없나용?? 
멤버변수에 바로 생성해서 여쭤보아요

2022-06-24 01:41 UTC, jpoh281 commented on lib/models/at_bat.dart
> +    if (answer.numbers[i] == batting.numbers[i]) {
커밋을 이렇게 달 수 있군요! 
다음부터는 해당 커밋을 댓글로 같이 달게요! 감사합니다.

2022-06-24 01:42 UTC, neoganjeol commented on lib/models/at_bat.dart
> +  final InningResult battingResult = InningResult();
@jpoh281
제가 잘 몰라서 그러는데 dart는 생성자에서 객체를 할당 해줄 수 없나용?? (2)

2022-06-24 01:42 UTC, neoganjeol commented on lib/models/at_bat.dart
> +    if (_isBall(i)) {
@jpoh281  한줄 띄워주는건 어떨까요?

2022-06-24 01:44 UTC, neoganjeol commented on lib/models/base_ball.dart
> +  List<Inning> innings = [];
@jpoh281  이곳뿐만아니라 접근제한자가  _(private)이 아닌 변수들이나 메소드들이 많이 보이던데 전부 public이여도 되는거에요?

2022-06-24 01:45 UTC, neoganjeol commented on lib/models/pitching_numbers.dart
> +    while (selectedNumbers.length < maxBat) {
@jpoh281  적당한 한줄 띄기가 있으면 보기 더 좋을거같아요

2022-06-24 01:46 UTC, neoganjeol commented on lib/models/pitching_numbers.dart
> +    var answers = selectedNumbers;
@jpoh281  왜 다른 변수로 한번 더 선언해주는거에요 ?? 궁금

2022-06-24 03:22 UTC, jpoh281 commented on lib/models/pitching_numbers.dart
> +    var answers = selectedNumbers;
https://github.com/jpoh281/base_ball_game/pull/1/commits/8dbb810fef7d19e606a3aea072350937ff5f7feb
불필요한 변수 선언으로 보여서 삭제했습니다.

2022-06-24 03:22 UTC, jpoh281 commented on lib/models/pitching_numbers.dart
> +    while (selectedNumbers.length < maxBat) {
https://github.com/jpoh281/base_ball_game/pull/1/commits/8dbb810fef7d19e606a3aea072350937ff5f7feb
추가했습니다!

2022-06-24 03:22 UTC, jpoh281 commented on lib/models/at_bat.dart
> +    if (_isBall(i)) {
https://github.com/jpoh281/base_ball_game/commit/8dbb810fef7d19e606a3aea072350937ff5f7feb
추가했습니다!

2022-06-24 03:35 UTC, jpoh281 commented on lib/controllers/base_ball_game_controller.dart
> +  final BaseBall game = BaseBall();
생성자 괄호 () 에서는 const(immutable) 객체들 밖에 못 생성해요.

 
![image](https://user-images.githubusercontent.com/54665433/175456877-7091096a-5bbd-4115-b862-5c7a18f52886.png)

그래서 필요한 경우 constructor initializer list를 사용해서 할 수 있지만, 위와 같이 그냥 변수로 대입해도 되는 상황이라면 그렇게 사용하는 것을 권장하고 있습니다.
이건 다트의 권장사양이에용

2022-06-24 03:39 UTC, jpoh281 commented on lib/controllers/base_ball_game_controller.dart
> +  final BaseBall game = BaseBall();
별개로 생성자 블록에서 처리할 수 있긴하지만, late를 붙여야되고 그게 더 지저분하게 만드는 방향이라고 판단되었어요.

2022-06-24 03:49 UTC, jpoh281 commented on lib/models/batting_numbers.dart
> +    if (regExpResult.length != 3) {
그렇다면 규칙에 관한 클래스를 하나 더 만들어야할 것 같아요.

2022-06-24 03:51 UTC, jpoh281 commented on lib/models/at_bat.dart
> +  final InningResult battingResult = InningResult();
위의 코멘트와 같습니다.

2022-06-24 03:56 UTC, jpoh281 commented on lib/models/base_ball.dart
> +  List<Inning> innings = [];
https://github.com/jpoh281/base_ball_game/pull/1/commits/8be6deef9e54f9d163d93e9ea966ff2364a5c2ba
일단 외부 호출이 없는 내부 필드를 private로 변경했습니다.
질문하시는 부분이 개발 상 가능의 여부인지, 다트 언어에서의 권장 여부인지 잘 모르겠어요.
개발상에서는 가능하기는 한데 제 생각에는 외부에서 호출하지 않는 것들은 private인게 맞다고 생각합니다....

2022-06-24 04:36 UTC, neoganjeol commented on lib/models/batting_numbers.dart
> +    if (regExpResult.length != 3) {
@jpoh281 네 좋으네요! 그렇게 쪼개가는거에요 !

2022-06-24 04:39 UTC, neoganjeol commented on lib/controllers/base_ball_game_controller.dart
> +  final BaseBall game = BaseBall();
@jpoh281  객체의 생성말고 이미 생성된 객체를 할당만 불가능한건가 해서요. 저렇게 생성자가 아닌 멤버변수를 바꿔야하거나 또는 테스트할때 주입할 수 가 없잖아요? 생성자 블록 사용법은 모르지만 https://brunch.co.kr/@mystoryg/123 해당 고수님의 설명을 보면 할당이 가능해 보이는데 변경하면 어떨까요?

2022-06-24 04:40 UTC, neoganjeol commented on lib/models/base_ball.dart
> +  List<Inning> innings = [];
@jpoh281  네네 외부호출하지않는것들을 private처리 했으면 하는거는 저도 동의하는데요. 대부분의 클래스의 멤버변수들이 public인 상태로 되어있어서 여쭤봤던거에요 private로 변경했으면해서요

2022-06-25 13:16 UTC, jpoh281 commented on lib/controllers/base_ball_game_controller.dart
> +  final BaseBall game = BaseBall();
생성자 주입받는 방식으로 변경하라고 말씀해주시는거죠? 
이런 느낌으로..?

확실히 테스트하려면 이게 훨씬 낫겠네요.

```dart
class Person{
     Person(this.name);
     
     final String name;

}
```

2022-06-26 15:07 UTC, jpoh281 commented
7943dfbbdd223fb25648847bd4e938b38fd43a7f 
커밋 명: BattingNumber -> Pitcher, PitchingNumber -> Batter 로 변경


유저가 매 턴 입력하는 것이 투수의 역할에 더 가깝고, 게임에서 정해진 답이 타자의 역할이라고 생각해서
다시 클래스명을 변경했습니다.

인덱스를 사용하지 않는 편이 좋다고 생각해 Iterator 를 적용 시켰습니다.
그 외에 내부 메소드들을 야구에 맞는 이름으로 변경 시켰습니다.



9fad7b7aa18d2c2f48a11d5dc9d6f442f35c69f0

AtBat(타수) -> PlateAppearance(타석)

타석에 섰을 때 투수와 타자가 대결을 한다고 생각해서 메소드 명을 compete 로 지었고,
또한 투수가 공을 던졌을 때 타자가 스윙을 했느냐, 보고있었느냐에 따라 볼 카운트를 심판이 판단한다고 생각해서 judgement 라는 변수명으로 BallCount를 조절하게 변경했습니다.
+

볼 카운트와 이닝 결과를 분리해서 볼 카운트는 과정에서 기록하는 역할을, 이닝 결과는 Immutable 하게 변경했습니다.



060f35674cbcd4c95193f75549dc1ef1eb39fd89

말씀해주신대로 테스트하기 편하도록 내부에서 생성하기 보다는 생성된 객체를 주입? 할당?받도록 변경시켰습니다. 


302da6304cb62519ece485ba1e9dabd1d709ccb6
처음 커밋에서 이터레이터를 사용하는게 좋다고 생각했었는데 구현을 하다보니 이터레이터를 초기화하지 못한다면
게임이 정상적으로 진행될 수 없다는 것을 깨달아서 다시 원래대로 돌렸습니다.

2022-06-26 15:08 UTC, jpoh281 commented
남은 일을 크게 나누면 

1. 룰을 유저에게  입력받아 작동하도록 만들기
2. 테스트코드 작성하기
라고 생각됩니다.

2022-06-26 15:25 UTC, neoganjeol requested changes
고생 많으셨어요! 코드가 점점 깔끔해지네요 ! 고민의 흔적이많이보이는데 조금 더 욕심내볼만한 코멘트를 남겼어요

2022-06-26 15:25 UTC, neoganjeol commented on lib/constants.dart
> +const int maxBat = 3;
@jpoh281  public 상수들을 따로 모아두는건 안티패턴으로 보는 경우도 있는데요 왜 그런지 한번 고민해보셔도 좋을듯 해요

2022-06-26 15:25 UTC, neoganjeol commented on lib/models/base_ball.dart
> +  }
@jpoh281  ? 이건 무엇이죠 ?

2022-06-26 15:25 UTC, neoganjeol commented on lib/models/base_ball.dart
> +    _innings.add(inning);
@jpoh281  innings를 클래스로 하나 만들어주면 어떨까요? 그러면 이렇게 데이터에 직접접근하는것도 한번 더 깜쌀수있을거같아요. 일급컬렉션으로 말이죠

2022-06-26 15:25 UTC, neoganjeol commented on lib/models/pitcher.dart
> +  final List<int> _numbers;
@jpoh281  이것도 위에서 말씀드린것처럼 한번 클래스로 만들어보는건 어떨까요? 그러면 pitch 메소드에서 새로운 클래스에 요청을 할거고 그럼 좀더 명시적으로 드러나겠죠 ?

2022-06-26 15:59 UTC, jpoh281 commented on lib/models/base_ball.dart
> +  }
9459c6c7c51bb266a64eced71bb933884d9f73b4
제거했습니다 부끄럽네요

2022-06-26 16:01 UTC, jpoh281 commented on lib/models/pitcher.dart
> +  final List<int> _numbers;
0004cfbc0f26e9ae59365b6747e49b5cbbb0847d

타자와 투수 둘 다 결국` List<int> _numbers`를 가지기때문에 BallMix(볼배합)이라는 클래스를 만들어서
타자는 약점이 되는 볼배합, 투수는 던지는 볼배합이 되도록 만들었습니다.

2022-06-27 15:50 UTC, jpoh281 commented
### 턴과 이닝을 입력받아서 게임을 진행하도록 변경

![image](https://user-images.githubusercontent.com/54665433/175979538-fb5174c6-5c6d-4a0c-884e-8513d569cfd5.png)

9459c6c7c51bb266a64eced71bb933884d9f73b4
의미없는 메소드 제거

0004cfbc0f26e9ae59365b6747e49b5cbbb0847d
타자와 투수로부터 일급 컬렉션인 BallMix를 만들어 분리

9235d3a3318f4dcaf52912909c2d9f807afdb009
Innings 일급 컬렉션을 만들어서 분리

27167f47ee6ed8526d606b152f507abb62cdcfaa
일단 사용자에게 룰을 입력받아서 게임을 진행하도록 만들고 싶어서 `late static` 키워드를 사용해서 입력하도록 변경했습니다.
그런데 코드가 훨씬 더 많이 지저분하게 변경된 것 같아서 이부분은 어떻게 깔끔하게 변화할 수 있을지 고민중입니다.

인터넷에 검색해봤을 때 ex) pi = 3.14159265352 라는 것이 있다면
글로벌 상수보단, 계산기라는 클래스의 static 상수로 존재하는게 낫다는 글을 봤는데 그렇게 되면 Innings의 경우 maxInning을 혼자 사용해서 쉽게 리팩토링이 가능한데, numberOfBat 상수의 경우는 이곳 저곳에서 사용해서 사용되는 부분들을 한곳으로 몰아줘야할지 고민입니다.

2022-06-27 15:52 UTC, jpoh281 commented on lib/constants.dart
> +const int maxBat = 3;
아래의 코멘트로 별도로 남겼지만 한번 더 적겠습니다.

https://github.com/jpoh281/base_ball_game/commit/27167f47ee6ed8526d606b152f507abb62cdcfaa
일단 사용자에게 룰을 입력받아서 게임을 진행하도록 만들고 싶어서 late static 키워드를 사용해서 입력하도록 변경했습니다.
그런데 코드가 훨씬 더 많이 지저분하게 변경된 것 같아서 이부분은 어떻게 깔끔하게 변화할 수 있을지 고민중입니다.

인터넷에 검색해봤을 때 ex) pi = 3.14159265352 라는 것이 있다면
글로벌 상수보단, 계산기라는 클래스의 static 상수로 존재하는게 낫다는 글을 봤는데 그렇게 되면 Innings의 경우 maxInning을 혼자 사용해서 쉽게 리팩토링이 가능한데, numberOfBat 상수의 경우는 이곳 저곳에서 사용해서 사용되는 부분들을 한곳으로 몰아줘야할지 고민입니다.

2022-06-27 15:52 UTC, jpoh281 commented on lib/models/base_ball.dart
> +    _innings.add(inning);
https://github.com/jpoh281/base_ball_game/commit/9235d3a3318f4dcaf52912909c2d9f807afdb009
Innings 일급 컬렉션을 만들어서 분리

2022-06-27 16:01 UTC, jpoh281 commented
0b32b27873fead74ca4616fc9d95609de887e0ca
다시 생각해보니 Rule이라는 곳에 상수로 모아두는 것보다 각 책임을 가지는 클래스?? 
예를들어 턴 종료의 책임을 가지는것은 baseball 혹은 innings 라고 생각해서 일단 innings 로 이동했습니다.
그리고 공의 수에 대한 값은 ballmix가 가지는게 맞다고 생각하여 이동시켰습니다.

2022-06-27 16:26 UTC, neoganjeol reviewed
점점 작아지는 클래스속에 역할과 책임이 명학해지는듯해요!
많이 노력하고 계신데 조금 더 고민해볼 만한 코멘트 드렸어요!

2022-06-27 16:26 UTC, neoganjeol commented on lib/controllers/base_ball_game_controller.dart
> +  BaseBallGameController(this.board, this.game);
👍

2022-06-27 16:26 UTC, neoganjeol commented on lib/controllers/base_ball_game_controller.dart
> +    if (result.isWin) {
줄 띄움을 해주면 더 읽기 좋을거 같아요!

2022-06-27 16:26 UTC, neoganjeol commented on lib/models/ball_mix.dart
> +  factory BallMix.fromUser(String? answer) {
user용과 자동생성 BalMix 두개가 필요한거죵?

2022-06-27 16:26 UTC, neoganjeol commented on lib/models/innings.dart
> +class Innings {
👍

2022-06-27 16:26 UTC, neoganjeol commented on lib/models/innings.dart
> +  static late final int maxInning;
static으로 선언해서 데이터를 계속 바꿔주는것보단 이것도 MaxIning이란 클래스를 만들고 Innings의 멤버변수로 관리 하는건 어떨까요??

2022-06-27 16:26 UTC, neoganjeol commented on lib/models/innings.dart
> +  static RegExp inningsRegExp = RegExp('[1-9]{1}\\d*');
이거는 어디서 사용하는거에요??

2022-06-27 16:26 UTC, neoganjeol commented on lib/models/innings.dart
> +  List<Inning> _innings = [];
멤버변수는 되도록이면 생성자에서 할당하도록 해주세요.

생성자를 두개 만들면 될거같아요 
제가 dart문법은 몰라서 자바 비스므리하게 대체할게요
```java

class Innings(List<Inning> innings) {
   this.innings = innings
}

class Innings() {
  this([]);
}

```

2022-06-27 16:26 UTC, neoganjeol commented on lib/models/innings.dart
> +  int get nowInning => _innings.length + 1;
욕심내면 NowInning 이란 클래스로 만들어보는건 어떨까요??

2022-06-27 16:26 UTC, neoganjeol commented on lib/models/innings.dart
> +  bool get isFull => _innings.length == maxInning;
위에서 말씀드린 코멘트처럼 MaxIning 라는 클래스를 만들게되면 이것도 이동할 수 있을듯한데 
어떻게 생각하세요 ?

2022-06-27 16:26 UTC, neoganjeol commented on lib/models/innings.dart
> +  void reset(){
사용되는 메소드일까요???

2022-06-27 16:26 UTC, neoganjeol commented on lib/models/inning_result.dart
> +  bool get isWin => _strikes == BallMix.numberOfBat;
data를 그대로 가져다 비교보다는 BalMix에게 물어보거나 해당 책임이 애매하다고 느껴지면 새로운 클래스를 만드는건 어떨가요?? 
isWin을 책임질 클래스요

2022-06-27 16:26 UTC, neoganjeol commented on lib/models/ball_mix.dart
> +  static late final int numberOfBat;
꼭 스태틱으로 관리를 해야하는걸까요??

2022-06-27 16:26 UTC, neoganjeol commented on lib/models/mound.dart
> +    for(int i = 0; i < BallMix.numberOfBat; i++){
이곳에서는 BallMix.numberOfBat값을 가져와야만 하는거겠죠??

2022-06-27 16:26 UTC, neoganjeol commented on lib/views/rule.dart
> +  static RegExp inningsRegExp = RegExp('[1-9]{1}\\d*');
RegExp 들을 enum이나 또는 별도 클래스로 따로 만들어서 관리해보는건 어떨까요??

2022-06-27 16:58 UTC, MyStoryG commented on lib/models/ball_mix.dart
> +  bool contains(int number) {
bool 형식에 보통 is붙여서 쓰지 않나요? 어떤 곳에서는 쓰셨고 여기에는 사용하지 않았네요.

2022-06-27 17:24 UTC, MyStoryG commented on lib/models/inning.dart
> +  late final InningResult _inningResult;
멤버 변수일 필요가 있나요?

2022-06-27 17:24 UTC, MyStoryG commented on lib/models/inning.dart
> +    return _inningResult;
멤버 변수에 굳이 담아서 리턴해야 할 이유가 있나요?

2022-06-27 17:27 UTC, MyStoryG commented on lib/models/mound.dart
> +  void judgement(int index, BallCount ballCount) {
함수명은 보통 명사로 잘 안쓰지 않나요?

2022-06-28 14:15 UTC, jpoh281 commented on lib/models/mound.dart
> +  void judgement(int index, BallCount ballCount) {
네 제가 놓친 부분같습니다. judge로 수정하겠습니다.

2022-06-28 14:21 UTC, jpoh281 commented on lib/models/ball_mix.dart
> +  bool contains(int number) {
dart의 list 메소드가 contains라서 그대로 사용했습니다.
contains의 경우는 그냥 A Contains B 이런식으로 사용하는 걸로 알고있어요!

아래의 글 참조했습니다.
https://jacking75.github.io/ETC_true_false_return_function_naming/

그럼에도 불구하고 is로 통일하는 컨벤션을 가지는게 좋다고 생각하시는지 아니면 이런식으로 사용해도 괜찮은지 생각 말씀해주시면 저도 앞으로 다른 팀원분들한테 이야기할 때 더 좋을 것 같아요.

2022-06-28 14:21 UTC, jpoh281 commented on lib/controllers/base_ball_game_controller.dart
> +    if (result.isWin) {
줄 띄움 부분이 몇번 지적당하네요.
좀 더 신경쓰겠습니다 ㅠㅠ 죄송합니다..

2022-06-28 14:23 UTC, jpoh281 commented on lib/models/innings.dart
> +  void reset(){
이 부분도 좀 더 신경썼어야 됐는데 놓쳤습니다 ㅠㅠ

2022-06-28 16:19 UTC, jpoh281 commented on lib/views/rule.dart
> +  static RegExp inningsRegExp = RegExp('[1-9]{1}\\d*');
f3b6ea62ab81599f04f49521500c4e718c45e2bf
이 부분이 두 가지로 해석됩니다.
1. RegExp를 담당하는 전체 클래스를 만든다.
2. 각 클래스 (NumberOfBat, MaxInning)에 검증 로직으로 넣는다.

저는 일단 Input Parser라는 클래스를 만들어서 유저 인풋으로부터의 검증을 모두 저 친구가 처리하도록 했습니다.

2022-06-28 16:20 UTC, jpoh281 commented on lib/models/rules/game_options.dart
>  }
@neoganjeol 
말씀하셨던 것과 같이 승리 패배 조건은 게임 옵션이라는 클래스에서 담당하도록 했습니다.

2022-06-28 16:22 UTC, jpoh281 commented on lib/models/inning.dart
> +    return _inningResult;
해당 이닝의 결과를 저장하려고 그랬습니다.
저장하는 이유는 toString에서 출력시키기 위함입니다.

2022-06-28 16:22 UTC, jpoh281 commented on lib/models/inning.dart
> +  late final InningResult _inningResult;
해당 이닝의 결과를 저장하려고 그랬습니다.
저장하는 이유는 toString에서 출력시키기 위함입니다.

2022-06-28 16:23 UTC, jpoh281 commented on lib/models/now_inning.dart
> +}
@neoganjeol 현재 이닝을 담당하는 클래스를 만들었습니다.

2022-06-28 16:25 UTC, jpoh281 commented on lib/models/innings.dart
> +  static RegExp inningsRegExp = RegExp('[1-9]{1}\\d*');
지웠습니다... 더 신경쓰도록 하겠습니다

2022-06-28 16:25 UTC, jpoh281 commented on lib/models/ball_mix.dart
> +  factory BallMix.fromUser(String? answer) {
https://github.com/jpoh281/base_ball_game/commit/f3b6ea62ab81599f04f49521500c4e718c45e2bf
저는 Input Parser라는 클래스를 만들어서 유저 인풋으로부터의 검증을 모두 저 친구가 처리하도록 했습니다.

2022-06-28 16:26 UTC, jpoh281 commented on lib/models/rules/max_innings.dart
> +}
@neoganjeol MaxInning 만들었습니당

2022-06-28 16:27 UTC, jpoh281 commented on lib/models/rules/game_options.dart
> +}
@neoganjeol  스태틱을 전부 없애고 주입받는 방식으로 변경했습니다.

2022-06-29 12:45 UTC, MyStoryG commented on lib/models/ball_mix.dart
> +  factory BallMix.fromUser(String? answer) {
selectedNumbers.add 독특한 방식이네요.
그냥 아래처럼 평범한 것만 떠올렸는데 이렇게도 하는군요!

for(int i; i < numberOfBat; i++) {
 selectedNumbers.add(numbers[i]);
}

2022-06-29 12:59 UTC, MyStoryG commented on lib/models/ball_mix.dart
> +  bool contains(int number) {
아하 list의 contains를 그대로 리턴하는거군요. 그런 측면이면 유지하는 게 좋을 것 같기도 하네요.
근데 _numbers의 getter를 제공하면 ofIndex()나 contains()는 불필요할 것 같은데 혹시 이유가 있나요?

2022-06-29 13:07 UTC, jpoh281 commented on lib/models/ball_mix.dart
> +  bool contains(int number) {
일급 컬렉션으로 만든 이유가 배열을 외부로부터 보호?하기 위해서라고 생각해서
직접 `_numbers` 변수를 건드리지 못하게 하고
ofIndex라는 메소드와 contains만 사용할 수 있도록 했습니다.

2022-06-29 13:22 UTC, MyStoryG commented on lib/models/ball_mix.dart
> +  bool contains(int number) {
불변성 때문이라면 어쩔 수가 없겠군요.

2022-07-02 01:56 UTC, merged